# Generated by Django 5.1.3 on 2025-02-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlerefreshtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Google Refresh Token', 'verbose_name_plural': 'Google Refresh Tokens'},
        ),
    ]
