# Generated by Django 5.1.3 on 2025-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_seed_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
