# Generated by Django 5.1.3 on 2025-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.SmallIntegerField(blank=True, default=30, null=True),
        ),
    ]
