# Generated by Django 5.1.3 on 2025-02-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercalendar',
            old_name='color',
            new_name='backgroundColor',
        ),
        migrations.AddField(
            model_name='usercalendar',
            name='owner',
            field=models.BooleanField(blank=True, default=True, help_text='Является ли пользователь владельцем календаря.'),
        ),
    ]
