# Generated by Django 5.1.3 on 2025-04-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalendar',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
