# Generated by Django 5.1.3 on 2025-02-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_color_usercalendar_backgroundcolor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercalendar',
            old_name='backgroundColor',
            new_name='background_color',
        ),
        migrations.RenameField(
            model_name='usercalendar',
            old_name='name',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='usercalendar',
            name='time_zone',
            field=models.CharField(blank=True, help_text='Часовой пояс календаря.', max_length=50, null=True),
        ),
    ]
