# Generated by Django 5.1.3 on 2026-01-04 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercalendar',
            old_name='calendar_id',
            new_name='google_calendar_id',
        ),
        migrations.AddConstraint(
            model_name='usercalendar',
            constraint=models.UniqueConstraint(fields=('user', 'google_calendar_id'), name='unique_user_calendar_id_when_owner_true'),
        ),
    ]
