# Generated by Django 5.1.3 on 2025-04-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_usercalendar_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercalendar',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='usercalendar',
            name='unique_calendar_id_when_owner_true',
        ),
    ]
